source 'https://rubygems.org'

gem 'rspec'
gem 'selenium-webdriver'
gem 'rails'
gem 'cucumber', '=2.4.0'
gem 'rack'
gem 'rake'
gem 'trollop'
gem 'require_all'
gem 'gherkin'
gem 'logger'
gem 'nio4r', '=2.2.0'